[package]
name = "vscode-install-tasks"
version = "0.1.0"
authors = ["Jeremy W. Rowe <jeremywrowe@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.6.2"
glob = "0.3.0"
