.TH GIT-CHURN 1
.SH NAME
git-churn \- list churn of each file in a git repository

.SH SYNOPSIS
.B git-churn
.IR folder ...
.IR file ...

.SH DESCRIPTION
.B git-churn
Allows you to at a glance look at all of the files that are changing in a git repository,
especially helpful when looking through an unfamiliar repository. Can take a list of files or folders to filter down your results.