.TH GIT-LOG-ADDED 1
.SH NAME
git-log-added \- Shows all added files in a git repository

.SH DESCRIPTION
.B git-log-added
Displays a git log for all added files in a git repository. Helpful for when you're looking
for recently added files when trying to debug something. All normal git log options are supported.
