# /Users/jeremyrowe/.config/tmuxinator/spree.yml

name: spree
root: /Volumes/Source/spreedly

windows:
  - core:
      root: /Volumes/Source/spreedly/core
      layout: main-vertical
      panes:
        - git fetch
  - id:
      root: /Volumes/Source/spreedly/id
      layout: main-vertical
      panes:
        - git fetch
  - fullstack:
      root: /Volumes/Source/spreedly/fullstack
      layout: main-vertical
      panes:
        - git fetch
  - dev-services: 
      root: /Volumes/Source/spreedly/dev-services
      layout: main-vertical
      panes:
        - git fetch
  - ngrok: 
      root: /Volumes/Source/spreedly/dev-services
      layout: main-vertical
      panes:
        - external-puma core.spreedly.test jrowe-core
