require 'open3'

HOME_PATH = ENV["HOME"]
BIN_PATH = File.join(HOME_PATH, "bin")
MAN_PATH = "/usr/local/man/man1"
OH_MY_ZSH_PATH = File.join(HOME_PATH, ".oh-my-zsh")
ZSH_AUTOSUGGESTIONS_PATH = File.join(OH_MY_ZSH_PATH, "custom", "plugins", "zsh-autosuggestions")
VIM_VUNDLE_PATH = File.join(HOME_PATH, ".vim")
HOMEBREW_PATH = "/usr/local/Homebrew"

desc "Setup a new machine - install brew, bin, man, and dotfiles"
task :install => ['ohmyzsh:install', 'bin:install', 'man:install', 'brew:install', 'dotfiles:install', 'vim:install']

file OH_MY_ZSH_PATH do
  Open3.capture2e(%[sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"])
end

file ZSH_AUTOSUGGESTIONS_PATH do
  Open3.capture2e(%[git clone https://github.com/zsh-users/zsh-autosuggestions #{ZSH_AUTOSUGGESTIONS_PATH}])
end

file VIM_VUNDLE_PATH do
  Open3.capture2e(%[git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim])
end

file HOMEBREW_PATH do
  Open3.capture2e(%[/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"])
end

file BIN_PATH do
  ln_s "#{HOME_PATH}/.dotfiles/setup/bin", BIN_PATH
  Open3.capture2e("chmod a+x #{HOME_PATH}/bin")
end

file MAN_PATH do
  `sudo mkdir -p /usr/local/man && sudo chown $USER /usr/local/man`
  ln_s "#{HOME_PATH}/.dotfiles/setup/man/man1", MAN_PATH
end

namespace :brew do
  desc "Install homebrew"
  task :install => [HOMEBREW_PATH, 'brew:packages']

  desc "Install homebrew packages"
  task :packages do
    Open3.capture2e("brew bundle")
  end
end

namespace :bin do
  desc "Install all personal binaries into ~/bin"
  task :install => [BIN_PATH]
end

namespace :man do
  desc "Install all personal man files into ~/man"
  task :install => [MAN_PATH]
end

namespace :dotfiles do
  desc "Install dotfiles using rcup"
  task :install do
    Open3.capture2e("yes | rcup -x setup")
  end
end

namespace :ohmyzsh do
  task :setup do
    Open3.capture2e(%[chsh -s /bin/zsh]) unless ENV["SHELL"].include?("zsh")
  end

  desc "Install oh-my-zsh and set shell to zsh"
  task :install => [:setup, OH_MY_ZSH_PATH, ZSH_AUTOSUGGESTIONS_PATH]
  task :install_oh_my_zsh => [:setup, OH_MY_ZSH_PATH]
  task :install_autosuggestions => [:setup, ZSH_AUTOSUGGESTIONS_PATH]
end

namespace :vim do
  desc "Install vundle and it's packages"
  task :install => [VIM_VUNDLE_PATH, :vundle]

  desc "Update vundle packages"
  task :vundle do
    Open3.capture2e("vim +BundleClean! +BundleInstall! +qa")
  end
end
